### PR TITLE
SB-29544 | Event and EventSet enhancements

### PR DESCRIPTION
**Pull request by karthik-tarento**

### CODE REVIEW

**Comment by karthik-tarento** [comment]
@maheshkumargangula - Pls review this PR

**Comment by maheshkumargangula** [comment]
@karthik-tarento - I have few questions about this PR to understand the changes. 
1. Why are we having a proxy for the sunbird knowlg event and eventset APIs.
2. Why are we checking for the participents list or count and how are you computing it. The existing Cassandra DB table design doesn't support querying this information.
3. The API calls (proxy) not handling all the HTTP error codes. Please check once.
Please connect with @reshmi-nair and schedule a call if you need more clarification on these.
Cc: @reshmi-nair

**Comment by karthik-tarento** [comment]
@maheshkumargangula -- update on the review comments.
Pointer 1 - The proxy events were used to verify the event / eventSet has participants before discarding or updating -- After discussing the functionality with @reshmi-nair - we agree these are duplicate APIs and will create a confusion when comparing event / eventSet APIs in KP - we added these here because course-service has the APIs to get the list API for given event (which is added in this PR) - we will raise a new PR to KP later for the our requirement for this verification.
Pointer 2 - Participant count is used to check any users enrolled in event or not. we are using existing implementation - which intern uses the "user_enrollments" table to get participant list. This uses "allow filtering" in cassandra DB query - discussed the same with @reshmi-nair too and we are not currently looking to optimise this. 
Pointer 3 - Will update this and use proper error codes and messages when raising a PR against KP.

Note - project-sunbird/sunbird-course-service/tree/release-4.8.0 -- fails to build with test cases, Hence CircleCI fails in this PR too.

**Comment by karthik-tarento** [comment]
@maheshkumargangula -- I could not find any other API in existing implementation which avoids "allow filtering" when querying against sunbird_courses.user_enrolments table in Cassandra.
The current list enrolment APIs also uses with "allow filtering" when querying against sunbird_courses.user_enrolments table -- since this table structure itself has 3 primary keys (userid, courseid, batchid) and doesn't have any clustering key or partition key.
Please let me know if any available options when in this particular use case - i.e. getting list of courses enrolled by user OR getting list of users for given batchId / courseId.
CC: @reshmi-nair

**Comment by maheshkumargangula** [comment]
@karthik-tarento - The list enrolments API uses the userid (which is the first column of the primary key) to fetch a specific user enrolments. We don't need "allow filtering" to fetch this and the API implementation is not using "allow filtering" in this scenario. We can have a call if you want any clarification about this.

The **participant list** API is deprecated so, I requested you to not to use the methods related to it. Using queries with "allow filtering" will create performance issues. 
cc: @vrayulu

**Comment by karthik-tarento** [comment]
@maheshkumargangula - Pls check email and let me know availability for call.

**Pull request closed without merging**
